# JANGAN RECODE MULU LOL BELAJAR CODING NGAPA 
# GANTENG DOANG GK BISA CODING OKWOWKOWK
# MINIMAL NGOMONG DULU KONTOL KALO MAU RECODE
# https://github.com/Shishigami-X

# UDAH GK OPEN SOURCE LAGI
# MAKANYA KALO OPEN SOURCE TUH DI RECODE IZIN DULU
# LU MIKIR LAH BANGSAT WAKTU MASIH JADI SC ASLINYA SUSAH DAPET IJO
# PAS GW RECODE GW YANG RACIK UA NYA JADI GACOR DPT IJO NYA
# KLO IZIN SIH GK MASALAH
# EMANG BUKAN GW AUTHOR NYA
# TAPI LU MIKIR BANGSAT PAS GW RECODE..GW RACIK UA NYA
# JADI MUDAH DAPET IJONYA
# KALO MASIH DPT CP MULU LUNYA AJA YANG GAK
# GANTENG WOKWOOWOWWKWKWOWKWOW
